# Site settings
encoding: UTF-8

title: Noah Mitsuhashi
email: nmitsuha@usc.edu
description: > # this means to ignore newlines until "baseurl:"
  Noah Mitsuhashi personal site
baseurl: "" # the subpath of your site, e.g. /blog
url: noahmitsuhashi.io
instagram_username: noah_morepartiesinla
github_username:  nmits
facebook_username: Noah Mitsuhashi

# Build settings
markdown: kramdown

theme: jekyll-theme-slate