# Site settings
encoding: UTF-8

title: Noah Mitsuhashi
email: me@noahmitsuhashi.io
description: > # this means to ignore newlines until "baseurl:"
  Noah Mitsuhashi personal site
baseurl: "" # the subpath of your site, e.g. /blog
url: noahmitsuhashi.io
github_username:  nmits
linkedin_username:  nmits
twitter_username: noahmits
crunchbase_username: noah-mitsuhashi

# Build settings
markdown: kramdown

theme: jekyll-theme-slate
